[tools]
# JS
node = "25.7"
bun = "latest"
"npm:ansible-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:some-sass-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
# "npm:typescript-language-server" = "latest"
# "npm:typescript" = "latest"

# Python
python = "3.12.12"
uv = "latest"
"pipx:black" = "latest"
"pipx:clangd" = "latest"
"pipx:clang-format" = "latest"
"pipx:ruff" = "latest"
"pipx:ruff-lsp" = "latest"
"pipx:sqlit-tui" = "latest"

# Golang
go = "latest"

# AI
opencode = "latest"
"npm:skills" = "latest"
"npm:opensrc" = "latest"
# "npm:agent-browser" = "latest"
# "npm:chrome-devtools-mcp" = "latest"
# "pipx:perplexity-mcp-server" = "latest"
# "npm:@perplexity-ai/mcp-server" = "latest"

# LSP
hadolint = "latest"
marksman = "latest"
pandoc = "latest"
shellcheck = "latest"
shfmt = "latest"
superhtml = "latest"
taplo = "latest"
terraform-ls = "latest"
tinymist = "latest"
typst = "latest"
typstyle = "latest"
ghorg = "latest"
buildifier = "latest"
buf = "latest"
# [protols](https://github.com/coder3101/protols/releases/tag/0.13.3)

# Utils
chisel = "latest"
cloudflared = "latest"
dust = "latest"
helix = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
rclone = "latest"
starship = "latest"
task = "latest"
terraform = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
btop = "latest"
github-cli = "latest"
# mc = "latest"

[tasks.install]
run = """
mise run pkg
mise run agent-browser
mise run pip
mise run golang
mise run npm
"""

[tasks.pkg]
run = """
set -euo pipefail
pkg="\
poppler-utils \
"
ins() {
  local pm="$1"
  sudo "$pm" install -y "$pkg"
}
for pm in apt-get dnf; do
  command -v "$pm" >/dev/null && ins "$pm" && exit 0
done
exit 1
"""

[tasks.agent-browser]
run = """
set -euo pipefail
wget https://github.com/vercel-labs/agent-browser/releases/latest/download/agent-browser-linux-x64 -O /usr/local/bin/agent-browser && chmod +x /usr/local/bin/agent-browser && exit 0
exit 1
"""

[tasks.pip]
run = """
set -euo pipefail
pip install --no-cache-dir --upgrade -r ~/.config/mise/requirements.txt && exit 0
exit 1
"""

[tasks.golang]
run = """
set -euo pipefail
go install golang.org/x/tools/gopls@latest && \
  go install github.com/go-delve/delve/cmd/dlv@latest && \
  go install golang.org/x/tools/cmd/goimports@latest && \
  go install github.com/nametake/golangci-lint-langserver@latest && \
  go install github.com/a-h/templ/cmd/templ@latest && \
  curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin && \
  exit 0
exit 1
"""

[tasks.npm]
run = """
set -euo pipefail
npm i -g \
	typescript \
	typescript-language-server \
	@vue/language-server \
	@vue/typescript-plugin \
  && exit 0
exit 1
"""

[tasks.prune]
run = """
set -euo pipefail
mise prune && \
  mise cache clear && \
  pip cache purge && \
  uv cache clean && \
  npm cache clean --force && \
  npm dedup && \
  rm -rf ~/.bun/install/cache && \
  rm -rf ~/.bun/cache && \
  exit 0
exit 1
"""

[settings]
idiomatic_version_file_enable_tools = []
