[tools]
# JS
node = "25.7"
bun = "latest"
"npm:ansible-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:some-sass-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
# "npm:typescript-language-server" = "latest"
# "npm:typescript" = "latest"

# Python
python = "3.12.13"
"asdf:asdf-community/asdf-uv" = "latest"
"pipx:black" = "latest"
"pipx:clangd" = "latest"
"pipx:clang-format" = "latest"
"pipx:ruff" = "latest"
"pipx:ruff-lsp" = "latest"
"pipx:sqlit-tui" = "latest"

# Golang
go = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
"github:coder3101/protols" = "latest"
"github:go-delve/delve" = "latest"
"github:a-h/templ" = "latest"

# AI
# opencode = "latest"
"npm:skills" = "latest"
"npm:opensrc" = "latest"
"npm:@oh-my-pi/pi-coding-agent" = "latest"
"github:lightpanda-io/browser" = "latest"
"github:vercel-labs/agent-browser" = "latest"
"github:iOfficeAI/OfficeCLI" = "latest"
# "github:angelnicolasc/graymatter" = "latest"
# "github:aaif-goose/goose" = "latest"
# "npm:@gitlawb/openclaude" = "latest"
# "npm:@mariozechner/pi-coding-agent" = "latest"
# "npm:agent-browser" = "latest"
# "npm:chrome-devtools-mcp" = "latest"

# LSP
hadolint = "latest"
marksman = "latest"
pandoc = "latest"
shellcheck = "latest"
shfmt = "latest"
superhtml = "latest"
taplo = "latest"
terraform-ls = "latest"
tinymist = "latest"
typst = "latest"
typstyle = "latest"
ghorg = "latest"
buildifier = "latest"
buf = "latest"
"github:Feel-ix-343/markdown-oxide" = "latest"
"github:iwe-org/iwe" = "latest"
"github:psauxwwf/simple-completion-language-server" = "latest"

# Utils
chisel = "latest"
cloudflared = "latest"
dust = "latest"
helix = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
rclone = "latest"
starship = "latest"
task = "latest"
terraform = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
btop = "latest"
github-cli = "latest"
gitleaks = "latest"
trufflehog = "latest"
ripgrep = "latest"
fd = "latest"
worktrunk = "latest"
llmfit = "latest"
"github:Achno/gowall" = "latest"
# "github:psauxwwf/olcrtc" = "latest"
"github:psauxwwf/t2s" = "latest"
"github:psauxwwf/krot" = "v05.13.17"
"github:psauxwwf/zema" = "latest"
"github:Julien-cpsn/ATAC" = "latest"
# "github:danmartuszewski/hop" = "latest"
# mc = "latest"

[tasks.install]
run = """
mise run wget
mise run pip
mise run golang
mise run npm
"""

[tasks.wget]
run = """
#!/usr/bin/env bash
set -euo pipefail
exit 0
"""

[tasks.pip]
run = """
#!/usr/bin/env bash
set -euo pipefail
pip install --no-cache-dir --upgrade -r ~/.config/mise/requirements.txt
exit 0
"""

[tasks.golang]
run = """
#!/usr/bin/env bash
set -euo pipefail
go install golang.org/x/tools/gopls@latest && \
  go install golang.org/x/tools/cmd/goimports@latest
exit 0
"""

[tasks.npm]
run = """
#!/usr/bin/env bash
set -euo pipefail
npm i -g \
	typescript \
	typescript-language-server \
	@vue/language-server \
	@vue/typescript-plugin
exit 0
"""

[tasks.prune]
run = """
#!/usr/bin/env bash
set -euo pipefail
mise prune && \
  mise cache clear && \
  pip cache purge && \
  uv cache clean && \
  npm cache clean --force && \
  npm dedup && \
  go clean -cache -modcache -testcache -fuzzcache && \
  rm -rf ~/.bun/install/cache && \
  rm -rf ~/.bun/cache
exit 0
"""

[settings]
idiomatic_version_file_enable_tools = []
