[tools]
# JS
node = "25.7"
bun = "latest"
"npm:ansible-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:some-sass-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
# "npm:typescript-language-server" = "latest"
# "npm:typescript" = "latest"

# Python
python = "3.12.12"
uv = "latest"
"pipx:black" = "latest"
"pipx:clangd" = "latest"
"pipx:clang-format" = "latest"
"pipx:ruff" = "latest"
"pipx:ruff-lsp" = "latest"
"pipx:sqlit-tui" = "latest"

# Golang
go = "latest"

# AI
opencode = "latest"
"npm:skills" = "latest"
"npm:opensrc" = "latest"
# "pipx:perplexity-mcp-server" = "latest"
# "npm:@perplexity-ai/mcp-server" = "latest"

# LSP
hadolint = "latest"
marksman = "latest"
pandoc = "latest"
shellcheck = "latest"
shfmt = "latest"
superhtml = "latest"
taplo = "latest"
terraform-ls = "latest"
tinymist = "latest"
typst = "latest"
typstyle = "latest"
ghorg = "latest"
buildifier = "latest"
buf = "latest"
# [protols](https://github.com/coder3101/protols/releases/tag/0.13.3)

# Utils
chisel = "latest"
cloudflared = "latest"
dust = "latest"
helix = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
rclone = "latest"
starship = "latest"
task = "latest"
terraform = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
btop = "latest"
github-cli = "latest"
# mc = "latest"

[settings]
idiomatic_version_file_enable_tools = []
